// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIs75iOJ5ZCJi1w0OhbI0-8-leoxFjgWs',
    appId: '1:961623198454:web:b6305743c95297d1577ad7',
    messagingSenderId: '961623198454',
    projectId: 'storeproject-1b17a',
    authDomain: 'storeproject-1b17a.firebaseapp.com',
    storageBucket: 'storeproject-1b17a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg2R49N_m81Ys9Vz3CvDnaFVHZtpjffD0',
    appId: '1:961623198454:android:69547341c0d7ec7c577ad7',
    messagingSenderId: '961623198454',
    projectId: 'storeproject-1b17a',
    storageBucket: 'storeproject-1b17a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrb665MH5DagA47zT2Bxo_FPxQeGZ7m0',
    appId: '1:961623198454:ios:efd4dc9cc382fdce577ad7',
    messagingSenderId: '961623198454',
    projectId: 'storeproject-1b17a',
    storageBucket: 'storeproject-1b17a.appspot.com',
    iosClientId: '961623198454-srnn13bb5qtcqdib64f0ftp4d0khdk88.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClrb665MH5DagA47zT2Bxo_FPxQeGZ7m0',
    appId: '1:961623198454:ios:efd4dc9cc382fdce577ad7',
    messagingSenderId: '961623198454',
    projectId: 'storeproject-1b17a',
    storageBucket: 'storeproject-1b17a.appspot.com',
    iosClientId: '961623198454-srnn13bb5qtcqdib64f0ftp4d0khdk88.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestorage',
  );
}
