// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqxPuRFRLkOqEULav5iQRnnB1wvvdKrFo',
    appId: '1:663135254172:web:67aadb9643276cc07d1f59',
    messagingSenderId: '663135254172',
    projectId: 'testproject-c83a8',
    authDomain: 'testproject-c83a8.firebaseapp.com',
    storageBucket: 'testproject-c83a8.appspot.com',
    measurementId: 'G-3TGEG7QR3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk51kAgLf7t9PfuHAb9xqgqvmbHxatj1A',
    appId: '1:663135254172:android:b49ab94519193df27d1f59',
    messagingSenderId: '663135254172',
    projectId: 'testproject-c83a8',
    storageBucket: 'testproject-c83a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4w-398urOHB2-6D-B4WV251cr0Ufvi6c',
    appId: '1:663135254172:ios:74b481649278028e7d1f59',
    messagingSenderId: '663135254172',
    projectId: 'testproject-c83a8',
    storageBucket: 'testproject-c83a8.appspot.com',
    iosClientId: '663135254172-jtpasmtvbr155fo1feev70i0jvprbrhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4w-398urOHB2-6D-B4WV251cr0Ufvi6c',
    appId: '1:663135254172:ios:74b481649278028e7d1f59',
    messagingSenderId: '663135254172',
    projectId: 'testproject-c83a8',
    storageBucket: 'testproject-c83a8.appspot.com',
    iosClientId: '663135254172-jtpasmtvbr155fo1feev70i0jvprbrhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
